name: smart_glove
description: "Cloud-Based Smart Glove Anemia Detection mobile app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Styling
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  shimmer: ^3.0.0

  # State Management & Routing
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0

  # Networking & APIs
  dio: ^5.4.2
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0

  # Local Storage
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0
  
  # Models & JSON Generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # PDF & Sharing
  pdf: ^3.10.8
  printing: ^5.12.0

  # Bluetooth
  flutter_blue_plus: ^1.29.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.4
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
