import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../domain/entities/user.dart';
import '../../domain/entities/scan_result.dart';

class PdfService {
  static Future<void> generateAndSharePdf({
    required User user,
    required ScanResult scan,
  }) async {
    final pdf = pw.Document();

    // Determine severity label based on Hb value
    String severity = 'Normal';
    if (scan.hemoglobinLevel < 7) {
      severity = 'Severe Anemia';
    } else if (scan.hemoglobinLevel < 11) {
      severity = 'Mid Anemia';
    } else if (scan.hemoglobinLevel < 13) {
      severity = 'Borderline Anemia';
    }

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(24),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Center(
                  child: pw.Text(
                    'Smart Glove Hemoglobin Report',
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue900,
                    ),
                  ),
                ),
                pw.SizedBox(height: 32),
                
                // Patient Details
                pw.Text('Patient Details', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Divider(),
                pw.SizedBox(height: 8),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Name: ${user.name}'),
                    pw.Text('Patient ID: ${user.patientId}'),
                  ],
                ),
                pw.SizedBox(height: 4),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Age: ${user.age}'),
                    pw.Text('Gender: ${user.gender}'),
                  ],
                ),
                pw.SizedBox(height: 32),
                
                // Scan Results
                pw.Text('Scan Result', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Divider(),
                pw.SizedBox(height: 8),
                pw.Text('Date: ${scan.date.toString().split(' ')[0]}'),
                pw.SizedBox(height: 8),
                pw.Text(
                  'Hemoglobin Level: ${scan.hemoglobinLevel.toStringAsFixed(1)} g/dL',
                  style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 8),
                pw.Text('Classification: ${scan.statusText}'),
                pw.SizedBox(height: 8),
                pw.Text('Severity: $severity'),
                
                pw.SizedBox(height: 48),
                
                // Doctor Consultation Note
                if (scan.isAnemic)
                  pw.Container(
                    padding: const pw.EdgeInsets.all(12),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.red50,
                      border: pw.Border.all(color: PdfColors.red, width: 1),
                      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                    ),
                    child: pw.Row(
                      children: [
                        pw.Icon(const pw.IconData(0xe000), color: PdfColors.red), // Warning icon placeholder
                        pw.SizedBox(width: 8),
                        pw.Text(
                          'NOTE: Please consult a doctor for a professional diagnosis.',
                          style: pw.TextStyle(color: PdfColors.red, fontWeight: pw.FontWeight.bold),
                        ),
                      ],
                    ),
                  ),
                  
                pw.Spacer(),
                pw.Center(
                  child: pw.Text(
                    'Generated by Smart Glove App',
                    style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'Hb_Report_${user.patientId}_${scan.date.toString().split(' ')[0]}.pdf',
    );
  }
}
