from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app.schemas.report import HemoglobinReportResponse


def render_hemoglobin_report_pdf(report: HemoglobinReportResponse) -> bytes:
    """
    Generate a simple, reliable PDF (no external system deps).
    The PDF is intentionally minimal; improve layout in later iterations.
    """
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    y = h - 20 * mm
    c.setFont("Helvetica-Bold", 16)
    c.drawString(20 * mm, y, "Smart Glove Hemoglobin Report")

    y -= 12 * mm
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, f"Report ID: {report.ReportId}")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Generated: {report.ReportGeneratedAt.isoformat()}")

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Patient")
    y -= 7 * mm
    c.setFont("Helvetica", 10)
    p = report.PatientDetails
    c.drawString(20 * mm, y, f"{p.Name} | Age: {p.Age} | Gender: {p.Gender} | Pregnant: {p.IsPregnant}")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Contact: {p.ContactNumber} | Email: {p.Email}")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Patient ID: {p.PatientId}")

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Scanner (Owner)")
    y -= 7 * mm
    c.setFont("Helvetica", 10)
    s = report.ScannerDetails
    c.drawString(20 * mm, y, f"{s.Name} | {s.Email} | {s.ContactNumber}")

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Result")
    y -= 7 * mm
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, f"Hemoglobin: {report.HemoglobinLevel:.2f} g/dL")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Status: {report.StatusText} (is_anemic={report.IsAnemic})")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Scan time: {report.ScanTimestamp.isoformat()}")

    y -= 12 * mm
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(20 * mm, y, "Generated by Smart Glove backend.")

    c.showPage()
    c.save()
    return buf.getvalue()

