from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app.schemas.report import HemoglobinReportResponse


def render_hemoglobin_report_pdf(report: HemoglobinReportResponse) -> bytes:
    """
    Generate a simple, reliable PDF (no external system deps).
    The PDF is intentionally minimal; improve layout in later iterations.
    """
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    y = h - 20 * mm
    c.setFont("Helvetica-Bold", 16)
    c.drawString(20 * mm, y, "Smart Glove Hemoglobin Report")

    y -= 12 * mm
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, f"Report ID: {report.report_id}")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Generated: {report.report_generated_at.isoformat()}")

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Patient")
    y -= 7 * mm
    c.setFont("Helvetica", 10)
    p = report.patient_details
    c.drawString(20 * mm, y, f"{p.name} | Age: {p.age} | Gender: {p.gender} | Pregnant: {p.is_pregnant}")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Contact: {p.contact_number} | Email: {p.email}")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Patient ID: {p.patient_id}")

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Scanner (Owner)")
    y -= 7 * mm
    c.setFont("Helvetica", 10)
    s = report.scanner_details
    c.drawString(20 * mm, y, f"{s.name} | {s.email} | {s.contact_number}")

    y -= 10 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "Result")
    y -= 7 * mm
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y, f"Hemoglobin: {report.hemoglobin_level:.2f} g/dL")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Status: {report.status_text} (is_anemic={report.is_anemic})")
    y -= 6 * mm
    c.drawString(20 * mm, y, f"Scan time: {report.scan_timestamp.isoformat()}")

    y -= 12 * mm
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(20 * mm, y, "Generated by Smart Glove backend.")

    c.showPage()
    c.save()
    return buf.getvalue()

